# Use a imagem oficial do PostgreSQL 14
FROM postgres:16

# Configurações do PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=postgres

# Expor a porta padrão do PostgreSQL
EXPOSE 5430
